# MySQL
MYSQL_HOST = '127.0.0.1'
MYSQL_PORT = 3306
MYSQL_USER = 'root'
MYSQL_PASSWORD = 'ruiying7709'
MYSQL_DATABASE = 'week10'
MYSQL_CHARSET = 'utf8mb4'
MYSQL_URL = (f'mysql+pymysql://{MYSQL_USER}:{MYSQL_PASSWORD}@{MYSQL_HOST}:'
             f'{MYSQL_PORT}/{MYSQL_DATABASE}?charset={MYSQL_CHARSET}')
